# -*- coding: utf-8 -*-
"""dataframe length

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqhsCU81tnGKPZBq9yAoI09jEHF_b486
"""

#Filter the DataFrame to include only the Pokémon with 'Speed' >= 80.
#How many Pokémon meet this criterion?
#Display this DataFrame using your preferred visualization method.

"""Create a method to filter the dataframe. The method should take the original dataframe (Pokemon dataframe), column (‘Speed’), value (80) as arguments. It needs to return a new filtered dataframe. (task 3) TRIIN


Create a method to return the number of pokemons that meet the criterion. The method needs to take the new filtered dataframe. It needs to return a number of pokemons. (task 3) KINTIJA


Create a method to visualize the data. The method needs to take the new filtered dataframe. You can decide yourself what kind of chart you want, surprise us! It returns the visual chart. (task 3) TRIIN
"""

def check_len(dataframe):
    nember_of_pokemons = dataframe.shape[0]
    return number_of_pokemons