# -*- coding: utf-8 -*-
"""Pokemon_water-type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzdIHK9Vql1k9mAi1Ov8yAWko2Ax8VBY
"""

water_pokemon = pokemon_df[pokemon_df['Type 1'] == 'Water']


percentage_water = (len(water_pokemon) / len(pokemon_df)) * 100