# -*- coding: utf-8 -*-
"""pokemon_speed_value.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVjPzTwVqwVoKsXxyPW-oaZowrErUnvh
"""

max_speed = pokemon_df['Speed'].max()
min_speed = pokemon_df['Speed'].min()

speed_difference = max_speed - min_speed