# -*- coding: utf-8 -*-
"""pokemon_speed_value.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVjPzTwVqwVoKsXxyPW-oaZowrErUnvh
"""

def min_speed(df):
    min_speed = df['Speed'].min()
    return min_speed
