# -*- coding: utf-8 -*-
"""Pokemon_water-type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzdIHK9Vql1k9mAi1Ov8yAWko2Ax8VBY
"""
def pokemon_water_percentage(df):
    water_pokemon = df[df['Type 1'] == 'Water']
    percentage_water = (len(water_pokemon) / len(df)) * 100
    return percentage_water
