# -*- coding: utf-8 -*-
"""read_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAeuT31zi5DmhJnXGF50ut8h2PGLf4q0
"""

import pandas as pd

def read_csv(data):
    data = pd.read_csv('/content/Pokemon.csv')
    return data

def get_percentage_of_type(df, column, pokemon_type):
    total_pokemon = len(df)
    type_count = df[df[column] == pokemon_type].shape[0]
    percentage = (type_count / total_pokemon) * 100
    return percentage

water_percentage = get_percentage_of_type(df, 'Type 1', 'Water')
    print(f"Percentage of Water-type Pokémons: {water_percentage:.2f}%")

def read_csv(file_path):
    data = pd.read_csv('/content/Pokemon.csv')
    return data

def get_max_speed(df, Speed):
    return df[Speed].max()

def get_max_speed(df, Speed):
    return df[column].max()
    max_speed = get_max_speed(df, 'Speed')

print(f"The maximum Speed value is: {max_speed}")

def get_min_speed(df, Speed):
    return df[Speed].min()
    min_speed = get_min_speed(df, 'Speed')

print(f"The minimum Speed value is: {min_speed}")

def get_speed_difference(df, Speed):
 max_value = df[Speed].max()
 min_value = df[Speed].min()
 difference = max_value - min_value
 return difference

speed_difference = get_speed_difference(df, 'Speed')
print(f"The difference is: {speed_difference}")

from Pokemon.csv import read_csv
from get_max_speed import get_max_speed
from get_min_speed import get_min_speed
from get_speed_difference import get_speed_difference
from utils import get_percentage_of_type

def main():
    file_path = '/content/Pokemon.csv'
    df = read_csv(file_path)

    # Step 2: Get the percentage of Water-type Pokémon
    water_percentage = get_percentage_of_type(df, 'Type 1', 'Water')
    print(f"Percentage of Water-type Pokémons: {water_percentage:.2f}%")

    # Step 3: Get the maximum speed
    max_speed = get_max_speed(df, 'Speed')
    print(f"The maximum Speed value is: {max_speed}")

    # Step 4: Get the difference in speed
    speed_difference = get_speed_difference(df, 'Speed')
    print(f"The difference between the maximum and minimum Speed values is: {speed_difference}")

if __name__ == "__main__":
    main()

python main.py