# -*- coding: utf-8 -*-
"""clean_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iX-ln7KZb4iC5AHW9Pm7Ybm2COHPwEC5
"""

import pandas as pd
dataset=pd.read_csv('/content/transaction_dataset(1).csv')

clean_data = dataset['Gender'].value_counts(dropna=False).reset_index()
clean_data.columns = ['Gender', 'Count']

clean_data.to_csv('/content/transaction_dataset_clean.csv')

clean_data.head()