# -*- coding: utf-8 -*-
"""clean_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iX-ln7KZb4iC5AHW9Pm7Ybm2COHPwEC5
"""
def process_data(dataframe):
    clean_data = dataframe['Gender'].value_counts(dropna=False)
    return clean_data
